from __future__ import annotations

import zipfile
from pathlib import Path
from typing import Any

from .fs_utils import ensure_dir
from .product_constants import TIMELINE_FILE_NAME


def build_download_zip(master_root: Path, destination: Path, manifest: dict[str, Any]) -> Path:
    ensure_dir(destination.parent)
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("README.md", build_download_readme(manifest))
        for item in manifest.get("items") or []:
            if not isinstance(item, dict):
                continue
            conversation_id = str(item.get("conversation_id") or item.get("id") or "")
            if not conversation_id:
                continue
            item_root = master_root / conversation_id
            archive.write(item_root / "convert_info.json", f"items/{conversation_id}/convert_info.json")
            archive.write(item_root / TIMELINE_FILE_NAME, f"items/{conversation_id}/{TIMELINE_FILE_NAME}")
    return destination


def build_download_readme(manifest: dict[str, Any]) -> str:
    source = manifest.get("source_export") if isinstance(manifest.get("source_export"), dict) else {}
    return "\n".join(
        [
            "# TimelineForChatGPT Export",
            "",
            "This package was generated by TimelineForChatGPT from a ChatGPT export ZIP.",
            "",
            "Contents:",
            "",
            "- `README.md`: this file.",
            "- `items/<conversation_id>/convert_info.json`: conversion metadata for one conversation.",
            "- `items/<conversation_id>/timeline.json`: final exported title and user / assistant / system messages in conversation order.",
            "",
            f"- Generated at: `{manifest.get('generated_at') or '-'}`",
            f"- Run ID: `{manifest.get('run_id') or '-'}`",
            f"- Source file: `{source.get('filename') or '-'}`",
            f"- Conversation count: `{manifest.get('item_count', 0)}`",
            "",
        ]
    )
